m1 <- J48(Species ~ ., data = iris)
summary(m1)
table(iris$Species, predict(m1))
if(require("party", quietly = TRUE)) plot(m1)
write_to_dot(m1)
library("Rgraphviz")
ff <- tempfile()
write_to_dot(m1, ff)
plot(agread(ff))
DF2 <- read.arff(system.file("arff", "contact-lenses.arff", package = "RWeka"))
m2 <- J48(`contact-lenses` ~ ., data = DF2)
table(DF2$`contact-lenses`, predict(m2))
if(require("party", quietly = TRUE)) plot(m2)
DF3 <- read.arff(system.file("arff", "cpu.arff", package = "RWeka"))
m3 <- M5P(class ~ ., data = DF3)
if(require("party", quietly = TRUE)) plot(m3)
DF4 <- read.arff(system.file("arff", "weather.arff", package = "RWeka"))
m4 <- LMT(play ~ ., data = DF4)
table(DF4$play, predict(m4))
if(require("mlbench", quietly = TRUE) && require("party", quietly = TRUE)) {
  data("PimaIndiansDiabetes", package = "mlbench")
  m5 <- J48(diabetes ~ ., data = PimaIndiansDiabetes, control = Weka_control(R = TRUE))
  plot(m5)
}

